# Generated by Django 2.0.6 on 2018-06-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeCalc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Algo name')),
                ('signal', models.CharField(max_length=1024, verbose_name='Signal')),
                ('trade', models.CharField(max_length=1024, verbose_name='Trade')),
                ('ticker', models.CharField(max_length=1024, verbose_name='Ticker')),
            ],
            options={
                'verbose_name': 'Trade algorithm',
                'verbose_name_plural': 'Trade algorithms',
            },
        ),
    ]
